apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
    - name: web
      image: web:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - { name: DBHOST,   value: "mysql.database.svc.cluster.local" }
        - { name: DBPORT,   value: "3306" }
        - { name: DBUSER,   value: "appuser" }
        - { name: DBPWD,    value: "apppass123" }
        - { name: DATABASE, value: "employees" }
