apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - name: http
      port: 5000
      targetPort: 8080
      nodePort: 30000
